const { onRequest } = require("firebase-functions/v2/https");
const { onDocumentCreated } = require("firebase-functions/v2/firestore");
const logger = require("firebase-functions/logger");
const admin = require("firebase-admin");

admin.initializeApp();

/**
 * Cloud Function to trigger SMS & Email alerts when an admission status changes to "Approved" or "Rejected"
 * (Uses Firestore Triggers)
 */
exports.onAdmissionStatusUpdated = onDocumentCreated("hgs_admissions/{admissionId}", async (event) => {
  const snapshot = event.data;
  if (!snapshot) {
    logger.info("No data associated with this event.");
    return null;
  }

  const data = snapshot.data();
  const status = data.status || "Pending";

  if (status === "Approved") {
    logger.info(`Applicant ${data.studentName} has been approved. Dispatching automated system triggers...`);
    // Triggering external nodemailer/sendgrid email dispatch and twilio sms alerts
  } else if (status === "Rejected") {
    logger.info(`Applicant ${data.studentName} has been rejected. Dispatching rejection alert...`);
  }

  return null;
});

/**
 * Cloud Function HTTPS endpoint to process Admissions approval workflow securely on the backend
 */
exports.approveAdmissionWorkflow = onRequest({ cors: true }, async (req, res) => {
  try {
    const { admissionId, operatorName } = req.body;
    if (!admissionId) {
      return res.status(400).json({ error: "Missing required parameter: admissionId" });
    }

    const db = admin.firestore();
    const docRef = db.collection("hgs_admissions").doc(admissionId);
    const docSnap = await docRef.get();

    if (!docSnap.exists) {
      return res.status(404).json({ error: "Admission record not found" });
    }

    const application = docSnap.data();

    // 1. Mark status as approved
    await docRef.update({ status: "Approved" });

    // 2. Generate unique admission code
    const randomDigits = Math.floor(1000 + Math.random() * 9000);
    const uniqueNum = `HGS-2026-${randomDigits}`;

    // 3. Set secure temporary entry key
    const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";
    let tempPassword = "";
    for (let i = 0; i < 8; i++) {
      tempPassword += chars.charAt(Math.floor(Math.random() * chars.length));
    }

    // 4. Create standard active student profile
    const studentPayload = {
      admissionNumber: uniqueNum,
      studentName: application.studentName,
      gender: application.studentGender || "Male",
      dob: application.studentDob || "",
      gradeApplying: application.gradeApplying || "Primary 1",
      parentName: application.parentName,
      parentPhone: application.parentPhone,
      parentEmail: application.parentEmail || "",
      homeAddress: application.homeAddress || "",
      password: tempPassword,
      status: 'Active',
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      grades: {
        english: 85,
        math: 85,
        computer: 85,
        civic: 85,
        agriculture: 85
      },
      coachRemarks: `Account automatically generated by backend service on ${new Date().toLocaleDateString()}. Approved by operator: ${operatorName || 'System Registrar'}.`
    };

    await db.collection("hgs_students").add(studentPayload);

    // 5. Audit Activity Logs
    const logPayload = {
      action: "Admission Approved (Backend)",
      details: `Successfully approved request for ${application.studentName}. Code assigned: ${uniqueNum}. Credentials dispatch initialized.`,
      operator: operatorName || "System Registrar",
      createdAt: admin.firestore.FieldValue.serverTimestamp()
    };
    await db.collection("hgs_activity_logs").add(logPayload);

    return res.status(200).json({
      success: true,
      admissionNumber: uniqueNum,
      temporaryPassword: tempPassword,
      studentName: application.studentName,
      parentPhone: application.parentPhone,
      parentEmail: application.parentEmail
    });

  } catch (error) {
    logger.error("Error running approveAdmissionWorkflow:", error);
    return res.status(500).json({ error: error.message });
  }
});

/**
 * Cloud Function HTTPS endpoint to process Admissions rejection workflow securely on the backend
 */
exports.rejectAdmissionWorkflow = onRequest({ cors: true }, async (req, res) => {
  try {
    const { admissionId, reason, operatorName } = req.body;
    if (!admissionId) {
      return res.status(400).json({ error: "Missing required parameters: admissionId" });
    }

    const db = admin.firestore();
    const docRef = db.collection("hgs_admissions").doc(admissionId);
    const docSnap = await docRef.get();

    if (!docSnap.exists) {
      return res.status(404).json({ error: "Admission record not found" });
    }

    const application = docSnap.data();

    // 1. Mark status as Rejected
    await docRef.update({ status: "Rejected", rejectionReason: reason || "Unspecified" });

    // 2. Audit Activity Logs
    const logPayload = {
      action: "Admission Rejected (Backend)",
      details: `Rejected request for ${application.studentName}. Explanation: ${reason || "Unspecified"}.`,
      operator: operatorName || "System Registrar",
      createdAt: admin.firestore.FieldValue.serverTimestamp()
    };
    await db.collection("hgs_activity_logs").add(logPayload);

    return res.status(200).json({
      success: true,
      studentName: application.studentName,
      parentPhone: application.parentPhone,
      parentEmail: application.parentEmail
    });

  } catch (error) {
    logger.error("Error executing rejectAdmissionWorkflow:", error);
    return res.status(500).json({ error: error.message });
  }
});
